#!/usr/bin/env bash

# To test:
# for i in {0..23}; do ./dmultiwall -m -s ~/wallpapers/dmultiwall/island/ -t $i; sleep 1; done


set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

usage() {
    cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-f] -p param_value arg1 [arg2...]

Script description here.

Available options:

-h, --help      Print this help and exit
-v, --verbose   Print script debug info
-f, --flag      Some flag description
-p, --param     Some param description
EOF
    exit
}

cleanup() {
    trap - SIGINT SIGTERM ERR EXIT
    # script cleanup here
}

setup_colors() {
    if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
        NOFORMAT='\033[0m'
        RED='\033[0;31m'
        GREEN='\033[0;32m'
        ORANGE='\033[0;33m'
        BLUE='\033[0;34m'
        PURPLE='\033[0;35m'
        CYAN='\033[0;36m'
        YELLOW='\033[1;33m'
    else
        NOFORMAT=''
        RED=''
        GREEN=''
        ORANGE=''
        BLUE=''
        PURPLE=''
        CYAN=''
        YELLOW=''
    fi
}

msg() {
    echo >&2 -e "${1-}"
}

die() {
    local msg=$1
    local code=${2-1} # default exit status 1
    msg "$msg"
    exit "$code"
}

hour=""

parse_params() {
    # default values of variables set from params
    MULTI="false"
    style=''

    while :; do
        case "${1-}" in
            -h | --help) usage ;;
            -v | --verbose) set -x ;;
            --no-color) NO_COLOR=1 ;;
            -m | --multi) MULTI="true" ;; # example flag
            -s | --style) # example named parameter
                style="${2-}"
                shift
                ;;
            -t | --hour) # example named parameter
                hour="${2-}"
                ;;
            -?*) die "Unknown option: $1" ;;
            *) break ;;
        esac
        shift
    done

    args=("$@")

    # check required params and arguments
    [[ -z "${style-}" ]] && die "Missing required parameter: --style | -s"
    # [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"

    return 0
}

set_wallpaper() {
    hour="${1:-}"

    wp1_folder="$style/wp1"
    wp1_extension="jpg"
    wp1="$wp1_folder/${hour}.${wp1_extension}"

    if [[ "${MULTI}" == "true" ]]; then
        msg "Setting multi wallpapers, hour: ${hour}"
        wp2_folder="$style/wp2"
        wp2_extension="jpg"
        wp2="$wp2_folder/${hour}.${wp2_extension}"
        feh --bg-fill "${wp1}" --bg-fill "${wp2}"
    else
        msg "Setting single wallpapers, hour: ${hour}"
        feh --bg-scale --no-xinerama "${wp1}"
    fi
}

parse_params "$@"
setup_colors

msg "${RED}Read parameters:${NOFORMAT}"
msg "- MULTI: ${MULTI}"
msg "- Style: ${style}"

if [ -z "${hour}"  ]; then
    hour=$(date +"%H")
fi

set_wallpaper "${hour}"
