#!/usr/bin/env bash
set -euo pipefail

VERSION='1.1.0'
HOURS=1

PAUSE="---"
FREET=" . "
OPTIM="Optimization methods"
SEMIN="Semantic intelligence"
SOFTA="Software analytics"
AUTOM="Automated software"

TIMETABLE=$(cat << _EOF_
|Monday|Tuesday|Wednesday|Thursday|Friday|
| - - - | - - - | - - - | - - - | - - - |
09-10:|${FREET}|${FREET}|${SEMIN}|${FREET}|${FREET}|
10-11:|${AUTOM}|${FREET}|${SEMIN}|${SOFTA}|${FREET}|
11-12:|${AUTOM}|${FREET}|${SOFTA}|${SOFTA}|${FREET}|
12-13:|${AUTOM}|${FREET}|${SOFTA}|${SOFTA}|${FREET}|
13-14:|${PAUSE}|${PAUSE}|${PAUSE}|${PAUSE}|${PAUSE}|
14-15:|${OPTIM}|${SEMIN}|${FREET}|${FREET}|${OPTIM}|
15-16:|${OPTIM}|${SEMIN}|${FREET}|${FREET}|${OPTIM}|
16-17:|${OPTIM}|${FREET}|${FREET}|${FREET}|${OPTIM}|
17-18:|${FREET}|${FREET}|${FREET}|${FREET}|${FREET}|
_EOF_
)

usage() { cat << _EOF_
Usage: lessons [OPTION]
Show the lessons.
     -a,    print all the lessons (weekly)
     -d,    print lessons of the specified day (default current day)
     -h,    display this help and exit
     -v,    output version information and exit

Exit status:
     0      if OK,
     1      if minor problems (e.g., wrong specified day)

License:
    License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

_EOF_
1>&2; exit 1; }

show-daily-lessons(){
    local DAY

    case "${1}" in
        Mon)
            DAY=1
            ;;
        Tue)
            DAY=2
            ;;
        Wed)
            DAY=3
            ;;
        Thu)
            DAY=4
            ;;
        Fri)
            DAY=5
            ;;
        *)
            echo "Wrong specified day"
            exit 1
            ;;
    esac

    DAY=$((DAY + 1))
    DAILY_LESSONS=$(echo "${TIMETABLE}" | awk  -F '|' "{print \$${HOURS} \"\t\" \$${DAY}}")
    echo "${DAILY_LESSONS}"
}

show-tomorrow-lessons(){
    show-daily-lessons "$(date --date 'next day' +%a)"
}

show-all-lessons(){
    ALL_LESSONS=$(echo "${TIMETABLE}" | column -s "|" -L -t)
    echo "${ALL_LESSONS}"
}

while getopts "atd:hv" o; do
    case "${o}" in
        a)
            echo "Show all lessons"
            show-all-lessons
            ;;
        t)
            echo "Show tomorrow lessons"
            show-tomorrow-lessons
            ;;
        d)
            DAY=${OPTARG:0:3}
            echo "Show lessons of ${DAY}"
            show-daily-lessons "${DAY}"
            ;;
        v)
            echo "Version: ${VERSION}"
            ;;
        h | *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if (( OPTIND == 1 )); then
   show-daily-lessons "$(date +%a)"
fi

exit 0
