#!/bin/bash

function safe-umount() {
    busy=true
    while $busy
    do
        if mountpoint -q "$1" ; then
            umount "$1" 2> /dev/null
            if [ $? -eq 0 ]; then
                busy=false
            else
                sleep 0.5
            fi
        else
            busy=false
        fi
    done
}

width=250
zenity --password --text="Your password Sir." --width=$width | encfs -S ~/.locker ~/locker
if [ $? -eq 0 ]; then
    cat ~/locker/$1 | xclip -sel clip
    safe-umount ~/locker &
    zenity --info --text="The content has been copied in clipboard Sir." --width=$width &
else
    zenity --error --text="Incorrect password" --width=$width &
fi
