#!/usr/bin/env bash
set -euo pipefail

# IMPORTANT:
# Edit /etc/pulse/default.pa
# from "load-module module-stream-restore" to "load-module module-stream-restore restore_device=false"

# Replace following with your outputs
# You can check available sinks with: pactl list short sinks
first_sink_pattern="pci-0000_2f_00.*\.analog-stereo"
second_sink_pattern="Logitech_PRO_X_Wireless_Gaming_Headset"

# Replace following with your inputs
# You can check available sources with: pactl list short sources
first_source_pattern="CMEDIA_Q9-1-00"
second_source_pattern="Logitech_PRO_X_Wireless_Gaming_Headset.*\.mono-fallback"

first_sink=$(pactl list short sinks | awk '{print $2}' | grep -P "$first_sink_pattern")
second_sink=$(pactl list short sinks | awk '{print $2}' | grep -P "$second_sink_pattern")

first_source=$(pactl list short sources | awk '{print $2}' | grep -P "$first_source_pattern")
second_source=$(pactl list short sources | awk '{print $2}' | grep -P "$second_source_pattern")

move-sink() {
    # Thanks to: https://gist.github.com/ruzickap/53080ade88544661afa52bc7c7892cf4
    INPUTS=$(pactl list sink-inputs short | cut -f 1)
    for i in $INPUTS; do
        pactl move-sink-input "$i" "${1}"
    done
}

move-source() {
    # Thanks to: https://gist.github.com/ruzickap/53080ade88544661afa52bc7c7892cf4
    OUTPUTS=$(pactl list source-outputs short | cut -f 1)
    for i in $OUTPUTS; do
        pactl move-source-output "$i" "${1}"
    done
}

enable-sink() {
    pactl set-default-sink "${1}"
    pactl set-sink-mute "${1}" false
    pactl set-sink-volume "${1}" 100%
    move-sink "${1}"
}

enable-source() {
    pactl set-default-source "${1}"
    pactl set-source-mute "${1}" false
    pactl set-source-volume "${1}" 100%
    move-source "${1}"
}

disable-sink() {
    pactl set-sink-mute "${1}" true
}

disable-source() {
    pactl set-source-mute "${1}" true
}

enable-first() {
    enable-sink "${first_sink}"
    enable-source "${first_source}"
}

disable-first() {
    disable-sink "${first_sink}"
    disable-source "${first_source}"
}

enable-second() {
    enable-sink "${second_sink}"
    enable-source "${second_source}"
}

disable-second() {
    disable-sink "${second_sink}"
    disable-source "${second_source}"
}

swap(){
    default_output=$(pactl get-default-sink)
    if [[ "$first_sink" == "$default_output" ]]; then
        enable-second
        disable-first
    else
        enable-first
        disable-second
    fi
}

swap
exit 0
